-- MySQL Script generated by MySQL Workbench
-- Sun Apr 23 17:05:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema anjd16
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema anjd16
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `anjd16` DEFAULT CHARACTER SET latin1 ;
USE `anjd16` ;

-- -----------------------------------------------------
-- Table `anjd16`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anjd16`.`Users` ;

CREATE TABLE IF NOT EXISTS `anjd16`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` CHAR(255) NOT NULL,
  `password` CHAR(255) NOT NULL,
  `role` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `anjd16`.`content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `anjd16`.`content` ;

CREATE TABLE IF NOT EXISTS `anjd16`.`content` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `path` CHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `slug` CHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `title` VARCHAR(120) CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `type` CHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `filter` VARCHAR(80) CHARACTER SET 'utf8' COLLATE 'utf8_swedish_ci' NULL DEFAULT NULL,
  `published` DATETIME NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT NULL,
  `deleted` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `path` (`path` ASC),
  UNIQUE INDEX `slug` (`slug` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_swedish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
